site_name: MkDocs Manual
site_url: https://Zakonn1k.github.io/MkDocs-manual/
theme:
  name: material

site_author: Zakonn1k
copyright: Zakonn1k, 2025

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
